baseURL = "https://purendu.com"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false
# disableLanguages = ["fr", "zh-cn"]

# 站点标题（语言特定标题在 languages.toml 中配置）

theme = "atomic-core"
[pagination]
  pagerSize = 10
enableRobotsTXT = true
# 清洁 URL（Hugo 默认非丑陋 URL），为明确性保留此配置
uglyURLs = false

# 输出格式：主页与分区支持 RSS，页面仅 HTML
[outputs]
  home    = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page    = ["HTML"]

# 永久链接（可按需扩展更多 Section）
[permalinks]
  news = "/news/:slug/"

# 分类法：保持轻量，后续可扩展作者/系列等
[taxonomies]
  tag = "tags"
  category = "categories"

# Sitemap 设置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# 隐私默认：尽量关闭外部追踪，保持专业与中立
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable     = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.youtube]
    privacyEnhanced = true

# 标记渲染：允许短代码与内联 HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# 压缩：默认 HTML 压缩
[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false

# 自定义参数：轻量品牌与联系占位，细化请移至 data/company.yaml
[params]
  brandName = "Purendu Ltd."
  brandTagline = "Nuclear Investment · Scientific, Prudent, Long-term"
  themeColor = "#0A4C8A" # 深蓝，金融友好
  accentColor = "#1572A1" # 次级蓝
  textColor = "#1A1A1A"
  mutedTextColor = "#6B7280"
  containerMax = "72rem"

  [params.contact]
    email = "support@purendu.com"
    phone = "+44 20 0000 0000"
    response_sla = "We will respond within 3–5 business days"

  [params.links]
    linkedin = ""
    github   = ""
